Repository dpc-sdp/tide_landing_page, pull requests merged in 2020-08, with the labels that each got.

#96 [SDPA-4193] moves intro_text to top
  composer.json
  config/install/core.entity_view_display.node.landing_page.default.yml
  dev-tools.sh
  tide_landing_page.install
Labels: Needs review

#97 [SDPA-4449] Add placeholder and helper text to Image Gallery
  config/install/core.entity_form_display.paragraph.media_gallery.default.yml
  config/install/field.field.paragraph.media_gallery.field_paragraph_media_gallery.yml
  tide_landing_page.install
Labels: Ready to be merged

#98 [SDPA-4451]CMS UI improvement - paragraph labels
  config/install/core.entity_form_display.paragraph.keydates.default.yml
  config/install/field.field.paragraph.keydates.field_paragraph_keydate.yml
  js/hide_elements.js
  tide_landing_page.install
  tide_landing_page.libraries.yml
  tide_landing_page.module
Labels: Ready for test

#102 Feature/adds addtional fields
  config/install/core.entity_form_display.paragraph.introduction_banner.default.yml
  config/install/core.entity_view_display.paragraph.introduction_banner.default.yml
  config/install/field.field.paragraph.introduction_banner.field_banner_display_type.yml
  config/install/field.field.paragraph.introduction_banner.field_banner_type.yml
  config/install/field.field.paragraph.introduction_banner.field_call_to_action_title.yml
  config/install/field.field.paragraph.introduction_banner.field_paragraph_body.yml
  config/install/field.field.paragraph.introduction_banner.field_paragraph_links.yml
  config/install/field.field.paragraph.introduction_banner.field_paragraph_summary.yml
  config/install/field.storage.paragraph.field_banner_display_type.yml
  config/install/field.storage.paragraph.field_banner_type.yml
  config/install/field.storage.paragraph.field_call_to_action_title.yml
  config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--introduction_banner.yml
  tests/behat/features/fields.feature
  tide_landing_page.info.yml
  tide_landing_page.install
  tide_landing_page.module
Labels: Ready for test

#101 [SDPA-4489] Added new paragraph type for openform and updated related config install files.
  config/install/core.entity_form_display.paragraph.form_embed_openforms.default.yml
  config/install/core.entity_view_display.paragraph.form_embed_openforms.default.yml
  config/install/field.field.node.landing_page.field_landing_page_component.yml
  config/install/field.field.paragraph.form_embed_openforms.field_form_link.yml
  config/install/field.storage.paragraph.field_form_link.yml
  config/install/paragraphs.paragraphs_type.embedded_webform.yml
  config/install/paragraphs.paragraphs_type.form_embed_openforms.yml
  config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--form_embed_openforms.yml
  tests/behat/features/fields.feature
  tide_landing_page.info.yml
  tide_landing_page.install
Labels: Needs review
